apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  # By default it is ClusterIP so even if you miss this property it is fine
  # This type will expose the application for internal service to service communication
  type: ClusterIP
  ports:
    # Post where the service is exposed
    - port: 80
    # port where the application is exposed
      targetPort: 80
  selector:
    # Select using pod labels
    app: myapp
    type: frontend