apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  # This type will expose the application for access from outside the cluster using the node ip and nodePort
  # This is only supported by some cloud providers and it fall backs to NodePort where it is not supported
  type: LoadBalancer
  ports:
    # Post where the service is exposed
    - port: 80
    # port where the application is exposed
      targetPort: 80
    # Port on the node where the application will be exposed
      nodePort: 30008
  selector:
    # Select using pod labels
    app: myapp
    type: frontend