apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 3
  template:
    metadata:
      name: nginx
      labels:
        app: frontend
    spec:
      containers:
        - name: nginx
          image: nginx